/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LoggedInRouteImport } from './routes/logged-in'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppVenuesRouteImport } from './routes/app/venues'
import { Route as AppIdentitiesRouteImport } from './routes/app/identities'
import { Route as AppFeatureFlagsRouteImport } from './routes/app/feature-flags'
import { Route as AppBotChatRouteImport } from './routes/app/bot-chat'
import { Route as AppTeamsIndexRouteImport } from './routes/app/teams/index'
import { Route as AppRankingsIndexRouteImport } from './routes/app/rankings/index'
import { Route as AppPlayersIndexRouteImport } from './routes/app/players/index'
import { Route as AppImportIndexRouteImport } from './routes/app/import/index'
import { Route as AppEventsIndexRouteImport } from './routes/app/events/index'
import { Route as AppTeamsIdRouteImport } from './routes/app/teams/$id'
import { Route as AppPlayersIdRouteImport } from './routes/app/players/$id'
import { Route as AppImportImportLongshanksRouteImport } from './routes/app/import/import-longshanks'
import { Route as AppImportImportBotRouteImport } from './routes/app/import/import-bot'
import { Route as AppEventsIdEditRouteImport } from './routes/app/events.$id.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggedInRoute = LoggedInRouteImport.update({
  id: '/logged-in',
  path: '/logged-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVenuesRoute = AppVenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIdentitiesRoute = AppIdentitiesRouteImport.update({
  id: '/identities',
  path: '/identities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFeatureFlagsRoute = AppFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBotChatRoute = AppBotChatRouteImport.update({
  id: '/bot-chat',
  path: '/bot-chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamsIndexRoute = AppTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRankingsIndexRoute = AppRankingsIndexRouteImport.update({
  id: '/rankings/',
  path: '/rankings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlayersIndexRoute = AppPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportIndexRoute = AppImportIndexRouteImport.update({
  id: '/import/',
  path: '/import/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIndexRoute = AppEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTeamsIdRoute = AppTeamsIdRouteImport.update({
  id: '/teams/$id',
  path: '/teams/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPlayersIdRoute = AppPlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppImportImportLongshanksRoute =
  AppImportImportLongshanksRouteImport.update({
    id: '/import/import-longshanks',
    path: '/import/import-longshanks',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppImportImportBotRoute = AppImportImportBotRouteImport.update({
  id: '/import/import-bot',
  path: '/import/import-bot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEventsIdEditRoute = AppEventsIdEditRouteImport.update({
  id: '/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/logged-in': typeof LoggedInRoute
  '/login': typeof LoginRoute
  '/app/bot-chat': typeof AppBotChatRoute
  '/app/feature-flags': typeof AppFeatureFlagsRoute
  '/app/identities': typeof AppIdentitiesRoute
  '/app/venues': typeof AppVenuesRoute
  '/app/import/import-bot': typeof AppImportImportBotRoute
  '/app/import/import-longshanks': typeof AppImportImportLongshanksRoute
  '/app/players/$id': typeof AppPlayersIdRoute
  '/app/teams/$id': typeof AppTeamsIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/import/': typeof AppImportIndexRoute
  '/app/players/': typeof AppPlayersIndexRoute
  '/app/rankings/': typeof AppRankingsIndexRoute
  '/app/teams/': typeof AppTeamsIndexRoute
  '/app/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/logged-in': typeof LoggedInRoute
  '/login': typeof LoginRoute
  '/app/bot-chat': typeof AppBotChatRoute
  '/app/feature-flags': typeof AppFeatureFlagsRoute
  '/app/identities': typeof AppIdentitiesRoute
  '/app/venues': typeof AppVenuesRoute
  '/app/import/import-bot': typeof AppImportImportBotRoute
  '/app/import/import-longshanks': typeof AppImportImportLongshanksRoute
  '/app/players/$id': typeof AppPlayersIdRoute
  '/app/teams/$id': typeof AppTeamsIdRoute
  '/app/events': typeof AppEventsIndexRoute
  '/app/import': typeof AppImportIndexRoute
  '/app/players': typeof AppPlayersIndexRoute
  '/app/rankings': typeof AppRankingsIndexRoute
  '/app/teams': typeof AppTeamsIndexRoute
  '/app/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/logged-in': typeof LoggedInRoute
  '/login': typeof LoginRoute
  '/app/bot-chat': typeof AppBotChatRoute
  '/app/feature-flags': typeof AppFeatureFlagsRoute
  '/app/identities': typeof AppIdentitiesRoute
  '/app/venues': typeof AppVenuesRoute
  '/app/import/import-bot': typeof AppImportImportBotRoute
  '/app/import/import-longshanks': typeof AppImportImportLongshanksRoute
  '/app/players/$id': typeof AppPlayersIdRoute
  '/app/teams/$id': typeof AppTeamsIdRoute
  '/app/events/': typeof AppEventsIndexRoute
  '/app/import/': typeof AppImportIndexRoute
  '/app/players/': typeof AppPlayersIndexRoute
  '/app/rankings/': typeof AppRankingsIndexRoute
  '/app/teams/': typeof AppTeamsIndexRoute
  '/app/events/$id/edit': typeof AppEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/logged-in'
    | '/login'
    | '/app/bot-chat'
    | '/app/feature-flags'
    | '/app/identities'
    | '/app/venues'
    | '/app/import/import-bot'
    | '/app/import/import-longshanks'
    | '/app/players/$id'
    | '/app/teams/$id'
    | '/app/events/'
    | '/app/import/'
    | '/app/players/'
    | '/app/rankings/'
    | '/app/teams/'
    | '/app/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/logged-in'
    | '/login'
    | '/app/bot-chat'
    | '/app/feature-flags'
    | '/app/identities'
    | '/app/venues'
    | '/app/import/import-bot'
    | '/app/import/import-longshanks'
    | '/app/players/$id'
    | '/app/teams/$id'
    | '/app/events'
    | '/app/import'
    | '/app/players'
    | '/app/rankings'
    | '/app/teams'
    | '/app/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/logged-in'
    | '/login'
    | '/app/bot-chat'
    | '/app/feature-flags'
    | '/app/identities'
    | '/app/venues'
    | '/app/import/import-bot'
    | '/app/import/import-longshanks'
    | '/app/players/$id'
    | '/app/teams/$id'
    | '/app/events/'
    | '/app/import/'
    | '/app/players/'
    | '/app/rankings/'
    | '/app/teams/'
    | '/app/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoggedInRoute: typeof LoggedInRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logged-in': {
      id: '/logged-in'
      path: '/logged-in'
      fullPath: '/logged-in'
      preLoaderRoute: typeof LoggedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/venues': {
      id: '/app/venues'
      path: '/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppVenuesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/identities': {
      id: '/app/identities'
      path: '/identities'
      fullPath: '/app/identities'
      preLoaderRoute: typeof AppIdentitiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/feature-flags': {
      id: '/app/feature-flags'
      path: '/feature-flags'
      fullPath: '/app/feature-flags'
      preLoaderRoute: typeof AppFeatureFlagsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/bot-chat': {
      id: '/app/bot-chat'
      path: '/bot-chat'
      fullPath: '/app/bot-chat'
      preLoaderRoute: typeof AppBotChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/teams/': {
      id: '/app/teams/'
      path: '/teams'
      fullPath: '/app/teams/'
      preLoaderRoute: typeof AppTeamsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rankings/': {
      id: '/app/rankings/'
      path: '/rankings'
      fullPath: '/app/rankings/'
      preLoaderRoute: typeof AppRankingsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/players/': {
      id: '/app/players/'
      path: '/players'
      fullPath: '/app/players/'
      preLoaderRoute: typeof AppPlayersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import/': {
      id: '/app/import/'
      path: '/import'
      fullPath: '/app/import/'
      preLoaderRoute: typeof AppImportIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/events/': {
      id: '/app/events/'
      path: '/events'
      fullPath: '/app/events/'
      preLoaderRoute: typeof AppEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/teams/$id': {
      id: '/app/teams/$id'
      path: '/teams/$id'
      fullPath: '/app/teams/$id'
      preLoaderRoute: typeof AppTeamsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/players/$id': {
      id: '/app/players/$id'
      path: '/players/$id'
      fullPath: '/app/players/$id'
      preLoaderRoute: typeof AppPlayersIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import/import-longshanks': {
      id: '/app/import/import-longshanks'
      path: '/import/import-longshanks'
      fullPath: '/app/import/import-longshanks'
      preLoaderRoute: typeof AppImportImportLongshanksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/import/import-bot': {
      id: '/app/import/import-bot'
      path: '/import/import-bot'
      fullPath: '/app/import/import-bot'
      preLoaderRoute: typeof AppImportImportBotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/events/$id/edit': {
      id: '/app/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/app/events/$id/edit'
      preLoaderRoute: typeof AppEventsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppBotChatRoute: typeof AppBotChatRoute
  AppFeatureFlagsRoute: typeof AppFeatureFlagsRoute
  AppIdentitiesRoute: typeof AppIdentitiesRoute
  AppVenuesRoute: typeof AppVenuesRoute
  AppImportImportBotRoute: typeof AppImportImportBotRoute
  AppImportImportLongshanksRoute: typeof AppImportImportLongshanksRoute
  AppPlayersIdRoute: typeof AppPlayersIdRoute
  AppTeamsIdRoute: typeof AppTeamsIdRoute
  AppEventsIndexRoute: typeof AppEventsIndexRoute
  AppImportIndexRoute: typeof AppImportIndexRoute
  AppPlayersIndexRoute: typeof AppPlayersIndexRoute
  AppRankingsIndexRoute: typeof AppRankingsIndexRoute
  AppTeamsIndexRoute: typeof AppTeamsIndexRoute
  AppEventsIdEditRoute: typeof AppEventsIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBotChatRoute: AppBotChatRoute,
  AppFeatureFlagsRoute: AppFeatureFlagsRoute,
  AppIdentitiesRoute: AppIdentitiesRoute,
  AppVenuesRoute: AppVenuesRoute,
  AppImportImportBotRoute: AppImportImportBotRoute,
  AppImportImportLongshanksRoute: AppImportImportLongshanksRoute,
  AppPlayersIdRoute: AppPlayersIdRoute,
  AppTeamsIdRoute: AppTeamsIdRoute,
  AppEventsIndexRoute: AppEventsIndexRoute,
  AppImportIndexRoute: AppImportIndexRoute,
  AppPlayersIndexRoute: AppPlayersIndexRoute,
  AppRankingsIndexRoute: AppRankingsIndexRoute,
  AppTeamsIndexRoute: AppTeamsIndexRoute,
  AppEventsIdEditRoute: AppEventsIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoggedInRoute: LoggedInRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
