#!/bin/bash
set -e

echo 'Eventually this will all be done with github actions!'

cd backend
./build-for-prod.sh

cd ../frontend
VITE_BACKEND_URL=$PROD_BACKEND_URL npx vite build #npm run build # will need to typescheck at SOME point


echo 'Running DB migrations...'
FLYWAY_USER=$PROD_DATABASE_USER FLYWAY_PASSWORD=$PROD_DATABASE_PASSWORD FLYWAY_URL=$PROD_FLYWAY_URL flyway migrate
cd ../infra
DATABASE_URL=$PROD_DATABASE_URL DISCORD_REDIRECT_URL=$PROD_DISCORD_REDIRECT_URL cdk deploy

cd ..

echo 'Deployed!'



