/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Faction {
  created_at: Generated<Timestamp | null>;
  hex_code: string;
  id: Generated<number>;
  name: string;
}

export interface FlywaySchemaHistory {
  checksum: number | null;
  description: string;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Timestamp>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface Membership {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  join_date: Generated<Timestamp | null>;
  left_date: Timestamp | null;
  player_id: number | null;
  team_id: number | null;
}

export interface Player {
  created_at: Generated<Timestamp | null>;
  discord_id: string;
  discord_username: string;
  id: Generated<number>;
  longshanks_id: string | null;
  longshanks_name: string | null;
  name: string;
}

export interface Result {
  created_at: Generated<Timestamp | null>;
  faction_id: number | null;
  id: Generated<number>;
  place: number | null;
  player_id: number | null;
  tourney_id: number | null;
}

export interface Team {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  name: string;
}

export interface Tourney {
  created_at: Generated<Timestamp | null>;
  date: Timestamp | null;
  id: Generated<number>;
  longshanks_id: string | null;
  name: string;
  organiser_id: number | null;
  venue: string | null;
}

export interface DB {
  faction: Faction;
  flyway_schema_history: FlywaySchemaHistory;
  membership: Membership;
  player: Player;
  result: Result;
  team: Team;
  tourney: Tourney;
}
