/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface DiscordUser {
  created_at: Generated<Timestamp | null>;
  discord_avatar_url: string | null;
  discord_display_name: string | null;
  discord_nickname: string | null;
  discord_user_id: string;
  discord_username: string | null;
}

export interface Faction {
  created_at: Generated<Timestamp | null>;
  emoji: string | null;
  hex_code: string;
  id: Generated<number>;
  longshanks_html_name: string;
  name: string;
  name_code: string;
  short_name: string;
}

export interface FactionSnapshot {
  batch_id: number;
  created_at: Generated<Timestamp>;
  declaration_rate: number;
  declarations: Generated<number>;
  faction_code: string | null;
  id: Generated<number>;
  points_per_declaration: number | null;
  rank: number;
  total_points: number;
}

export interface FactionSnapshotBatch {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
}

export interface FlywaySchemaHistory {
  checksum: number | null;
  description: string;
  execution_time: number;
  installed_by: string;
  installed_on: Generated<Timestamp>;
  installed_rank: number;
  script: string;
  success: boolean;
  type: string;
  version: string | null;
}

export interface GeographyColumns {
  coord_dimension: number | null;
  f_geography_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface GeometryColumns {
  coord_dimension: number | null;
  f_geometry_column: string | null;
  f_table_catalog: string | null;
  f_table_name: string | null;
  f_table_schema: string | null;
  srid: number | null;
  type: string | null;
}

export interface IdentityProvider {
  id: string;
  name: string;
}

export interface Membership {
  created_at: Generated<Timestamp | null>;
  id: Generated<number>;
  is_captain: Generated<boolean>;
  join_date: Generated<Timestamp | null>;
  left_date: Timestamp | null;
  player_id: number | null;
  team_id: number | null;
}

export interface PaintingCategory {
  id: Generated<number>;
  name: string;
  tourney_id: number;
}

export interface PaintingWinner {
  category_id: number | null;
  id: Generated<number>;
  model: string;
  player_id: number;
  position: number;
}

export interface Player {
  created_at: Generated<Timestamp | null>;
  discord_id: string | null;
  id: Generated<number>;
  longshanks_name: string | null;
  name: string;
}

export interface PlayerIdentity {
  created_at: Generated<Timestamp | null>;
  external_id: string;
  id: Generated<number>;
  identity_provider_id: string;
  player_id: number | null;
  provider_name: string;
}

export interface RankingSnapshot {
  batch_id: number;
  player_id: number;
  rank: number;
  total_points: number;
}

export interface RankingSnapshotBatch {
  created_at: Generated<Timestamp>;
  id: Generated<number>;
  type_code: string;
}

export interface RankingSnapshotEvent {
  batch_id: number;
  player_id: number;
  tourney_id: number;
}

export interface RankingSnapshotType {
  code: string;
  description: string | null;
  discord_channel_id: string | null;
  display: Generated<boolean | null>;
  display_order: number | null;
  generate: Generated<boolean | null>;
  hex_code: string | null;
  name: string;
}

export interface Result {
  created_at: Generated<Timestamp | null>;
  faction_code: string;
  id: Generated<number>;
  place: number | null;
  player_identity_id: number;
  points: number;
  rounds_played: number;
  tourney_id: number | null;
}

export interface SpatialRefSys {
  auth_name: string | null;
  auth_srid: number | null;
  proj4text: string | null;
  srid: number;
  srtext: string | null;
}

export interface Team {
  brand_colour: string | null;
  created_at: Generated<Timestamp | null>;
  description: string | null;
  id: Generated<number>;
  image_key: string | null;
  name: string;
  venue_id: number | null;
}

export interface Tier {
  code: string;
  description: string | null;
  name: string | null;
}

export interface Tourney {
  bot_id: string | null;
  created_at: Generated<Timestamp | null>;
  date: Timestamp;
  days: Generated<number>;
  discord_post_id: string | null;
  id: Generated<number>;
  is_submitted: Generated<boolean>;
  longshanks_id: string | null;
  name: string;
  number_of_players: number;
  organiser_discord_id: string | null;
  rounds: Generated<number>;
  submitted: Generated<boolean | null>;
  tier_code: Generated<string | null>;
  venue: string | null;
  venue_id: number | null;
}

export interface Venue {
  geom: string | null;
  id: Generated<number>;
  name: string | null;
  post_code: string | null;
  town: string | null;
}

export interface DB {
  discord_user: DiscordUser;
  faction: Faction;
  faction_snapshot: FactionSnapshot;
  faction_snapshot_batch: FactionSnapshotBatch;
  flyway_schema_history: FlywaySchemaHistory;
  geography_columns: GeographyColumns;
  geometry_columns: GeometryColumns;
  identity_provider: IdentityProvider;
  membership: Membership;
  painting_category: PaintingCategory;
  painting_winner: PaintingWinner;
  player: Player;
  player_identity: PlayerIdentity;
  ranking_snapshot: RankingSnapshot;
  ranking_snapshot_batch: RankingSnapshotBatch;
  ranking_snapshot_event: RankingSnapshotEvent;
  ranking_snapshot_type: RankingSnapshotType;
  result: Result;
  spatial_ref_sys: SpatialRefSys;
  team: Team;
  tier: Tier;
  tourney: Tourney;
  venue: Venue;
}
