export enum Faction {
  RESSERS = "RESSERS",
  GUILD = "GUILD",
  ARCANISTS = "ARCANISTS",
  OUTCASTS = "OUTCASTS",
  THUNDERS = "THUNDERS",
  NEVERBORN = "NEVERBORN",
  BAYOU = "BAYOU",
  EXPLORER = "EXPLORER",
}

export enum RankingType {
  BEST_FOREVER = "BEST_FOREVER",
  MASTERS = "MASTERS",
  BEST_RESSER = "BEST_RESSER",
  BEST_GUILD = "BEST_GUILD",
  BEST_ARCANIST = "BEST_ARCANIST",
  BEST_OUTCAST = "BEST_OUTCAST",
  BEST_THUNDER = "BEST_THUNDERS",
  BEST_NEVERBORN = "BEST_NEVERBORN",
  BEST_BAYOU = "BEST_BAYOU",
  BEST_EXPLORER = "BEST_EXPLORERS",
}
