/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpcomingEventsRouteImport } from './routes/upcoming-events'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TeamRankingsRouteImport } from './routes/team-rankings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FactionRankingsRouteImport } from './routes/faction-rankings'
import { Route as EventsRouteImport } from './routes/events'
import { Route as BestPaintedRouteImport } from './routes/best-painted'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpcomingEventIdRouteImport } from './routes/upcoming-event.$id'
import { Route as TeamIdRouteImport } from './routes/team.$id'
import { Route as PlayerIdRouteImport } from './routes/player.$id'
import { Route as EventIdRouteImport } from './routes/event.$id'

const UpcomingEventsRoute = UpcomingEventsRouteImport.update({
  id: '/upcoming-events',
  path: '/upcoming-events',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRankingsRoute = TeamRankingsRouteImport.update({
  id: '/team-rankings',
  path: '/team-rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FactionRankingsRoute = FactionRankingsRouteImport.update({
  id: '/faction-rankings',
  path: '/faction-rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPaintedRoute = BestPaintedRouteImport.update({
  id: '/best-painted',
  path: '/best-painted',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingEventIdRoute = UpcomingEventIdRouteImport.update({
  id: '/upcoming-event/$id',
  path: '/upcoming-event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdRoute = TeamIdRouteImport.update({
  id: '/team/$id',
  path: '/team/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerIdRoute = PlayerIdRouteImport.update({
  id: '/player/$id',
  path: '/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdRoute = EventIdRouteImport.update({
  id: '/event/$id',
  path: '/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-painted': typeof BestPaintedRoute
  '/events': typeof EventsRoute
  '/faction-rankings': typeof FactionRankingsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/players': typeof PlayersRoute
  '/rankings': typeof RankingsRoute
  '/regions': typeof RegionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-rankings': typeof TeamRankingsRoute
  '/teams': typeof TeamsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/event/$id': typeof EventIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$id': typeof TeamIdRoute
  '/upcoming-event/$id': typeof UpcomingEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-painted': typeof BestPaintedRoute
  '/events': typeof EventsRoute
  '/faction-rankings': typeof FactionRankingsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/players': typeof PlayersRoute
  '/rankings': typeof RankingsRoute
  '/regions': typeof RegionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-rankings': typeof TeamRankingsRoute
  '/teams': typeof TeamsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/event/$id': typeof EventIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$id': typeof TeamIdRoute
  '/upcoming-event/$id': typeof UpcomingEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-painted': typeof BestPaintedRoute
  '/events': typeof EventsRoute
  '/faction-rankings': typeof FactionRankingsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/players': typeof PlayersRoute
  '/rankings': typeof RankingsRoute
  '/regions': typeof RegionsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team-rankings': typeof TeamRankingsRoute
  '/teams': typeof TeamsRoute
  '/upcoming-events': typeof UpcomingEventsRoute
  '/event/$id': typeof EventIdRoute
  '/player/$id': typeof PlayerIdRoute
  '/team/$id': typeof TeamIdRoute
  '/upcoming-event/$id': typeof UpcomingEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-painted'
    | '/events'
    | '/faction-rankings'
    | '/how-it-works'
    | '/players'
    | '/rankings'
    | '/regions'
    | '/sitemap.xml'
    | '/team-rankings'
    | '/teams'
    | '/upcoming-events'
    | '/event/$id'
    | '/player/$id'
    | '/team/$id'
    | '/upcoming-event/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/best-painted'
    | '/events'
    | '/faction-rankings'
    | '/how-it-works'
    | '/players'
    | '/rankings'
    | '/regions'
    | '/sitemap.xml'
    | '/team-rankings'
    | '/teams'
    | '/upcoming-events'
    | '/event/$id'
    | '/player/$id'
    | '/team/$id'
    | '/upcoming-event/$id'
  id:
    | '__root__'
    | '/'
    | '/best-painted'
    | '/events'
    | '/faction-rankings'
    | '/how-it-works'
    | '/players'
    | '/rankings'
    | '/regions'
    | '/sitemap.xml'
    | '/team-rankings'
    | '/teams'
    | '/upcoming-events'
    | '/event/$id'
    | '/player/$id'
    | '/team/$id'
    | '/upcoming-event/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestPaintedRoute: typeof BestPaintedRoute
  EventsRoute: typeof EventsRoute
  FactionRankingsRoute: typeof FactionRankingsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PlayersRoute: typeof PlayersRoute
  RankingsRoute: typeof RankingsRoute
  RegionsRoute: typeof RegionsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRankingsRoute: typeof TeamRankingsRoute
  TeamsRoute: typeof TeamsRoute
  UpcomingEventsRoute: typeof UpcomingEventsRoute
  EventIdRoute: typeof EventIdRoute
  PlayerIdRoute: typeof PlayerIdRoute
  TeamIdRoute: typeof TeamIdRoute
  UpcomingEventIdRoute: typeof UpcomingEventIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upcoming-events': {
      id: '/upcoming-events'
      path: '/upcoming-events'
      fullPath: '/upcoming-events'
      preLoaderRoute: typeof UpcomingEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-rankings': {
      id: '/team-rankings'
      path: '/team-rankings'
      fullPath: '/team-rankings'
      preLoaderRoute: typeof TeamRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faction-rankings': {
      id: '/faction-rankings'
      path: '/faction-rankings'
      fullPath: '/faction-rankings'
      preLoaderRoute: typeof FactionRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-painted': {
      id: '/best-painted'
      path: '/best-painted'
      fullPath: '/best-painted'
      preLoaderRoute: typeof BestPaintedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-event/$id': {
      id: '/upcoming-event/$id'
      path: '/upcoming-event/$id'
      fullPath: '/upcoming-event/$id'
      preLoaderRoute: typeof UpcomingEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id': {
      id: '/team/$id'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof TeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$id': {
      id: '/player/$id'
      path: '/player/$id'
      fullPath: '/player/$id'
      preLoaderRoute: typeof PlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id': {
      id: '/event/$id'
      path: '/event/$id'
      fullPath: '/event/$id'
      preLoaderRoute: typeof EventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestPaintedRoute: BestPaintedRoute,
  EventsRoute: EventsRoute,
  FactionRankingsRoute: FactionRankingsRoute,
  HowItWorksRoute: HowItWorksRoute,
  PlayersRoute: PlayersRoute,
  RankingsRoute: RankingsRoute,
  RegionsRoute: RegionsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRankingsRoute: TeamRankingsRoute,
  TeamsRoute: TeamsRoute,
  UpcomingEventsRoute: UpcomingEventsRoute,
  EventIdRoute: EventIdRoute,
  PlayerIdRoute: PlayerIdRoute,
  TeamIdRoute: TeamIdRoute,
  UpcomingEventIdRoute: UpcomingEventIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
