#!/bin/bash

AUTH_HEADER='Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijg4NjkyMDQ0Mzg4ODUzMzUxNCIsInVzZXJuYW1lIjoiZ2FydGh0aGV3aXphcmQiLCJnbG9iYWxfbmFtZSI6IkphbWVzIFdpbHNvbiIsImlhdCI6MTc2NTgzODQ0NCwiZXhwIjoxNzk3Mzk2MDQ0fQ.GZ000eYw6fr85wlyqJ3oUkvxsUQe8F95JVeSLFA4YbQ'

curl -X POST localhost:9999/v1/longshanks-event/21816 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/longshanks-event/21815 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/longshanks-event/24148 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/longshanks-event/26373 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/longshanks-event/22198 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/longshanks-event/25681 -H "$AUTH_HEADER"