#!/bin/bash

AUTH_HEADER=$DEV_JWT_TOKEN_HEADER

curl -X POST localhost:9999/v1/longshanks-event/21816 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/generate-rankings -H "$AUTH_HEADER"

curl -X POST localhost:9999/v1/longshanks-event/21815 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/generate-rankings -H "$AUTH_HEADER"

curl -X POST localhost:9999/v1/longshanks-event/24148 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/generate-rankings -H "$AUTH_HEADER"

curl -X POST localhost:9999/v1/longshanks-event/26373 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/generate-rankings -H "$AUTH_HEADER"

curl -X POST localhost:9999/v1/longshanks-event/22198 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/generate-rankings -H "$AUTH_HEADER"

curl -X POST localhost:9999/v1/longshanks-event/25681 -H "$AUTH_HEADER"
curl -X POST localhost:9999/v1/generate-rankings -H "$AUTH_HEADER"

