/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedInRouteImport } from './routes/logged-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SiteRankingsRouteImport } from './routes/site/rankings'
import { Route as SiteFactionRankingsRouteImport } from './routes/site/faction-rankings'
import { Route as SiteEventsRouteImport } from './routes/site/events'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as AppDiscordMappingRouteImport } from './routes/app/discord-mapping'
import { Route as SitePlayerIdRouteImport } from './routes/site/player.$id'
import { Route as SiteEventIdRouteImport } from './routes/site/event.$id'
import { Route as AppAppPagesVenuesRouteImport } from './routes/app/_app-pages/venues'
import { Route as AppAppPagesImportBotRouteImport } from './routes/app/_app-pages/import-bot'
import { Route as AppAppPagesBotChatRouteImport } from './routes/app/_app-pages/bot-chat'
import { Route as AppAppPagesEventsIndexRouteImport } from './routes/app/_app-pages/events/index'
import { Route as AppAppPagesEventsNewManualRouteImport } from './routes/app/_app-pages/events/new-manual'
import { Route as AppAppPagesEventsNewLongshanksRouteImport } from './routes/app/_app-pages/events/new-longshanks'
import { Route as AppAppPagesEventsNewBotRouteImport } from './routes/app/_app-pages/events/new-bot'
import { Route as AppAppPagesEventsIdEditRouteImport } from './routes/app/_app-pages/events.$id.edit'

const LoggedInRoute = LoggedInRouteImport.update({
  id: '/logged-in',
  path: '/logged-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRankingsRoute = SiteRankingsRouteImport.update({
  id: '/site/rankings',
  path: '/site/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteFactionRankingsRoute = SiteFactionRankingsRouteImport.update({
  id: '/site/faction-rankings',
  path: '/site/faction-rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteEventsRoute = SiteEventsRouteImport.update({
  id: '/site/events',
  path: '/site/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDiscordMappingRoute = AppDiscordMappingRouteImport.update({
  id: '/app/discord-mapping',
  path: '/app/discord-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const SitePlayerIdRoute = SitePlayerIdRouteImport.update({
  id: '/site/player/$id',
  path: '/site/player/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteEventIdRoute = SiteEventIdRouteImport.update({
  id: '/site/event/$id',
  path: '/site/event/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppPagesVenuesRoute = AppAppPagesVenuesRouteImport.update({
  id: '/app/_app-pages/venues',
  path: '/app/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppPagesImportBotRoute = AppAppPagesImportBotRouteImport.update({
  id: '/app/_app-pages/import-bot',
  path: '/app/import-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppPagesBotChatRoute = AppAppPagesBotChatRouteImport.update({
  id: '/app/_app-pages/bot-chat',
  path: '/app/bot-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppPagesEventsIndexRoute = AppAppPagesEventsIndexRouteImport.update({
  id: '/app/_app-pages/events/',
  path: '/app/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppPagesEventsNewManualRoute =
  AppAppPagesEventsNewManualRouteImport.update({
    id: '/app/_app-pages/events/new-manual',
    path: '/app/events/new-manual',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAppPagesEventsNewLongshanksRoute =
  AppAppPagesEventsNewLongshanksRouteImport.update({
    id: '/app/_app-pages/events/new-longshanks',
    path: '/app/events/new-longshanks',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAppPagesEventsNewBotRoute = AppAppPagesEventsNewBotRouteImport.update({
  id: '/app/_app-pages/events/new-bot',
  path: '/app/events/new-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppPagesEventsIdEditRoute = AppAppPagesEventsIdEditRouteImport.update({
  id: '/app/_app-pages/events/$id/edit',
  path: '/app/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logged-in': typeof LoggedInRoute
  '/app/discord-mapping': typeof AppDiscordMappingRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/site/events': typeof SiteEventsRoute
  '/site/faction-rankings': typeof SiteFactionRankingsRoute
  '/site/rankings': typeof SiteRankingsRoute
  '/app': typeof AppIndexRoute
  '/app/bot-chat': typeof AppAppPagesBotChatRoute
  '/app/import-bot': typeof AppAppPagesImportBotRoute
  '/app/venues': typeof AppAppPagesVenuesRoute
  '/site/event/$id': typeof SiteEventIdRoute
  '/site/player/$id': typeof SitePlayerIdRoute
  '/app/events/new-bot': typeof AppAppPagesEventsNewBotRoute
  '/app/events/new-longshanks': typeof AppAppPagesEventsNewLongshanksRoute
  '/app/events/new-manual': typeof AppAppPagesEventsNewManualRoute
  '/app/events': typeof AppAppPagesEventsIndexRoute
  '/app/events/$id/edit': typeof AppAppPagesEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logged-in': typeof LoggedInRoute
  '/app/discord-mapping': typeof AppDiscordMappingRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/site/events': typeof SiteEventsRoute
  '/site/faction-rankings': typeof SiteFactionRankingsRoute
  '/site/rankings': typeof SiteRankingsRoute
  '/app': typeof AppIndexRoute
  '/app/bot-chat': typeof AppAppPagesBotChatRoute
  '/app/import-bot': typeof AppAppPagesImportBotRoute
  '/app/venues': typeof AppAppPagesVenuesRoute
  '/site/event/$id': typeof SiteEventIdRoute
  '/site/player/$id': typeof SitePlayerIdRoute
  '/app/events/new-bot': typeof AppAppPagesEventsNewBotRoute
  '/app/events/new-longshanks': typeof AppAppPagesEventsNewLongshanksRoute
  '/app/events/new-manual': typeof AppAppPagesEventsNewManualRoute
  '/app/events': typeof AppAppPagesEventsIndexRoute
  '/app/events/$id/edit': typeof AppAppPagesEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logged-in': typeof LoggedInRoute
  '/app/discord-mapping': typeof AppDiscordMappingRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/site/events': typeof SiteEventsRoute
  '/site/faction-rankings': typeof SiteFactionRankingsRoute
  '/site/rankings': typeof SiteRankingsRoute
  '/app/': typeof AppIndexRoute
  '/app/_app-pages/bot-chat': typeof AppAppPagesBotChatRoute
  '/app/_app-pages/import-bot': typeof AppAppPagesImportBotRoute
  '/app/_app-pages/venues': typeof AppAppPagesVenuesRoute
  '/site/event/$id': typeof SiteEventIdRoute
  '/site/player/$id': typeof SitePlayerIdRoute
  '/app/_app-pages/events/new-bot': typeof AppAppPagesEventsNewBotRoute
  '/app/_app-pages/events/new-longshanks': typeof AppAppPagesEventsNewLongshanksRoute
  '/app/_app-pages/events/new-manual': typeof AppAppPagesEventsNewManualRoute
  '/app/_app-pages/events/': typeof AppAppPagesEventsIndexRoute
  '/app/_app-pages/events/$id/edit': typeof AppAppPagesEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logged-in'
    | '/app/discord-mapping'
    | '/demo/tanstack-query'
    | '/site/events'
    | '/site/faction-rankings'
    | '/site/rankings'
    | '/app'
    | '/app/bot-chat'
    | '/app/import-bot'
    | '/app/venues'
    | '/site/event/$id'
    | '/site/player/$id'
    | '/app/events/new-bot'
    | '/app/events/new-longshanks'
    | '/app/events/new-manual'
    | '/app/events'
    | '/app/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logged-in'
    | '/app/discord-mapping'
    | '/demo/tanstack-query'
    | '/site/events'
    | '/site/faction-rankings'
    | '/site/rankings'
    | '/app'
    | '/app/bot-chat'
    | '/app/import-bot'
    | '/app/venues'
    | '/site/event/$id'
    | '/site/player/$id'
    | '/app/events/new-bot'
    | '/app/events/new-longshanks'
    | '/app/events/new-manual'
    | '/app/events'
    | '/app/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/logged-in'
    | '/app/discord-mapping'
    | '/demo/tanstack-query'
    | '/site/events'
    | '/site/faction-rankings'
    | '/site/rankings'
    | '/app/'
    | '/app/_app-pages/bot-chat'
    | '/app/_app-pages/import-bot'
    | '/app/_app-pages/venues'
    | '/site/event/$id'
    | '/site/player/$id'
    | '/app/_app-pages/events/new-bot'
    | '/app/_app-pages/events/new-longshanks'
    | '/app/_app-pages/events/new-manual'
    | '/app/_app-pages/events/'
    | '/app/_app-pages/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoggedInRoute: typeof LoggedInRoute
  AppDiscordMappingRoute: typeof AppDiscordMappingRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  SiteEventsRoute: typeof SiteEventsRoute
  SiteFactionRankingsRoute: typeof SiteFactionRankingsRoute
  SiteRankingsRoute: typeof SiteRankingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAppPagesBotChatRoute: typeof AppAppPagesBotChatRoute
  AppAppPagesImportBotRoute: typeof AppAppPagesImportBotRoute
  AppAppPagesVenuesRoute: typeof AppAppPagesVenuesRoute
  SiteEventIdRoute: typeof SiteEventIdRoute
  SitePlayerIdRoute: typeof SitePlayerIdRoute
  AppAppPagesEventsNewBotRoute: typeof AppAppPagesEventsNewBotRoute
  AppAppPagesEventsNewLongshanksRoute: typeof AppAppPagesEventsNewLongshanksRoute
  AppAppPagesEventsNewManualRoute: typeof AppAppPagesEventsNewManualRoute
  AppAppPagesEventsIndexRoute: typeof AppAppPagesEventsIndexRoute
  AppAppPagesEventsIdEditRoute: typeof AppAppPagesEventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logged-in': {
      id: '/logged-in'
      path: '/logged-in'
      fullPath: '/logged-in'
      preLoaderRoute: typeof LoggedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/rankings': {
      id: '/site/rankings'
      path: '/site/rankings'
      fullPath: '/site/rankings'
      preLoaderRoute: typeof SiteRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/faction-rankings': {
      id: '/site/faction-rankings'
      path: '/site/faction-rankings'
      fullPath: '/site/faction-rankings'
      preLoaderRoute: typeof SiteFactionRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/events': {
      id: '/site/events'
      path: '/site/events'
      fullPath: '/site/events'
      preLoaderRoute: typeof SiteEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/discord-mapping': {
      id: '/app/discord-mapping'
      path: '/app/discord-mapping'
      fullPath: '/app/discord-mapping'
      preLoaderRoute: typeof AppDiscordMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/player/$id': {
      id: '/site/player/$id'
      path: '/site/player/$id'
      fullPath: '/site/player/$id'
      preLoaderRoute: typeof SitePlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/event/$id': {
      id: '/site/event/$id'
      path: '/site/event/$id'
      fullPath: '/site/event/$id'
      preLoaderRoute: typeof SiteEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/venues': {
      id: '/app/_app-pages/venues'
      path: '/app/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppAppPagesVenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/import-bot': {
      id: '/app/_app-pages/import-bot'
      path: '/app/import-bot'
      fullPath: '/app/import-bot'
      preLoaderRoute: typeof AppAppPagesImportBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/bot-chat': {
      id: '/app/_app-pages/bot-chat'
      path: '/app/bot-chat'
      fullPath: '/app/bot-chat'
      preLoaderRoute: typeof AppAppPagesBotChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/events/': {
      id: '/app/_app-pages/events/'
      path: '/app/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppAppPagesEventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/events/new-manual': {
      id: '/app/_app-pages/events/new-manual'
      path: '/app/events/new-manual'
      fullPath: '/app/events/new-manual'
      preLoaderRoute: typeof AppAppPagesEventsNewManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/events/new-longshanks': {
      id: '/app/_app-pages/events/new-longshanks'
      path: '/app/events/new-longshanks'
      fullPath: '/app/events/new-longshanks'
      preLoaderRoute: typeof AppAppPagesEventsNewLongshanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/events/new-bot': {
      id: '/app/_app-pages/events/new-bot'
      path: '/app/events/new-bot'
      fullPath: '/app/events/new-bot'
      preLoaderRoute: typeof AppAppPagesEventsNewBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app-pages/events/$id/edit': {
      id: '/app/_app-pages/events/$id/edit'
      path: '/app/events/$id/edit'
      fullPath: '/app/events/$id/edit'
      preLoaderRoute: typeof AppAppPagesEventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoggedInRoute: LoggedInRoute,
  AppDiscordMappingRoute: AppDiscordMappingRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  SiteEventsRoute: SiteEventsRoute,
  SiteFactionRankingsRoute: SiteFactionRankingsRoute,
  SiteRankingsRoute: SiteRankingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppAppPagesBotChatRoute: AppAppPagesBotChatRoute,
  AppAppPagesImportBotRoute: AppAppPagesImportBotRoute,
  AppAppPagesVenuesRoute: AppAppPagesVenuesRoute,
  SiteEventIdRoute: SiteEventIdRoute,
  SitePlayerIdRoute: SitePlayerIdRoute,
  AppAppPagesEventsNewBotRoute: AppAppPagesEventsNewBotRoute,
  AppAppPagesEventsNewLongshanksRoute: AppAppPagesEventsNewLongshanksRoute,
  AppAppPagesEventsNewManualRoute: AppAppPagesEventsNewManualRoute,
  AppAppPagesEventsIndexRoute: AppAppPagesEventsIndexRoute,
  AppAppPagesEventsIdEditRoute: AppAppPagesEventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
