/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoggedInRouteImport } from './routes/logged-in'
import { Route as SiteRouteRouteImport } from './routes/site/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteSitePagesRankingsRouteImport } from './routes/site/_site-pages/rankings'
import { Route as SiteSitePagesFactionRankingsRouteImport } from './routes/site/_site-pages/faction-rankings'
import { Route as SiteSitePagesEventsRouteImport } from './routes/site/_site-pages/events'
import { Route as AppAppPagesVenuesRouteImport } from './routes/app/_app-pages/venues'
import { Route as AppAppPagesImportBotRouteImport } from './routes/app/_app-pages/import-bot'
import { Route as AppAppPagesIdentitiesRouteImport } from './routes/app/_app-pages/identities'
import { Route as AppAppPagesBotChatRouteImport } from './routes/app/_app-pages/bot-chat'
import { Route as AppAppPagesEventsIndexRouteImport } from './routes/app/_app-pages/events/index'
import { Route as SiteSitePagesPlayerIdRouteImport } from './routes/site/_site-pages/player.$id'
import { Route as SiteSitePagesEventIdRouteImport } from './routes/site/_site-pages/event.$id'
import { Route as AppAppPagesEventsNewManualRouteImport } from './routes/app/_app-pages/events/new-manual'
import { Route as AppAppPagesEventsNewLongshanksRouteImport } from './routes/app/_app-pages/events/new-longshanks'
import { Route as AppAppPagesEventsNewBotRouteImport } from './routes/app/_app-pages/events/new-bot'
import { Route as AppAppPagesEventsIdEditRouteImport } from './routes/app/_app-pages/events.$id.edit'

const LoggedInRoute = LoggedInRouteImport.update({
  id: '/logged-in',
  path: '/logged-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteSitePagesRankingsRoute = SiteSitePagesRankingsRouteImport.update({
  id: '/_site-pages/rankings',
  path: '/rankings',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteSitePagesFactionRankingsRoute =
  SiteSitePagesFactionRankingsRouteImport.update({
    id: '/_site-pages/faction-rankings',
    path: '/faction-rankings',
    getParentRoute: () => SiteRouteRoute,
  } as any)
const SiteSitePagesEventsRoute = SiteSitePagesEventsRouteImport.update({
  id: '/_site-pages/events',
  path: '/events',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AppAppPagesVenuesRoute = AppAppPagesVenuesRouteImport.update({
  id: '/_app-pages/venues',
  path: '/venues',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppPagesImportBotRoute = AppAppPagesImportBotRouteImport.update({
  id: '/_app-pages/import-bot',
  path: '/import-bot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppPagesIdentitiesRoute = AppAppPagesIdentitiesRouteImport.update({
  id: '/_app-pages/identities',
  path: '/identities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppPagesBotChatRoute = AppAppPagesBotChatRouteImport.update({
  id: '/_app-pages/bot-chat',
  path: '/bot-chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppPagesEventsIndexRoute = AppAppPagesEventsIndexRouteImport.update({
  id: '/_app-pages/events/',
  path: '/events/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SiteSitePagesPlayerIdRoute = SiteSitePagesPlayerIdRouteImport.update({
  id: '/_site-pages/player/$id',
  path: '/player/$id',
  getParentRoute: () => SiteRouteRoute,
} as any)
const SiteSitePagesEventIdRoute = SiteSitePagesEventIdRouteImport.update({
  id: '/_site-pages/event/$id',
  path: '/event/$id',
  getParentRoute: () => SiteRouteRoute,
} as any)
const AppAppPagesEventsNewManualRoute =
  AppAppPagesEventsNewManualRouteImport.update({
    id: '/_app-pages/events/new-manual',
    path: '/events/new-manual',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAppPagesEventsNewLongshanksRoute =
  AppAppPagesEventsNewLongshanksRouteImport.update({
    id: '/_app-pages/events/new-longshanks',
    path: '/events/new-longshanks',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppAppPagesEventsNewBotRoute = AppAppPagesEventsNewBotRouteImport.update({
  id: '/_app-pages/events/new-bot',
  path: '/events/new-bot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAppPagesEventsIdEditRoute = AppAppPagesEventsIdEditRouteImport.update({
  id: '/_app-pages/events/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/site': typeof SiteRouteRouteWithChildren
  '/logged-in': typeof LoggedInRoute
  '/app/bot-chat': typeof AppAppPagesBotChatRoute
  '/app/identities': typeof AppAppPagesIdentitiesRoute
  '/app/import-bot': typeof AppAppPagesImportBotRoute
  '/app/venues': typeof AppAppPagesVenuesRoute
  '/site/events': typeof SiteSitePagesEventsRoute
  '/site/faction-rankings': typeof SiteSitePagesFactionRankingsRoute
  '/site/rankings': typeof SiteSitePagesRankingsRoute
  '/app/events/new-bot': typeof AppAppPagesEventsNewBotRoute
  '/app/events/new-longshanks': typeof AppAppPagesEventsNewLongshanksRoute
  '/app/events/new-manual': typeof AppAppPagesEventsNewManualRoute
  '/site/event/$id': typeof SiteSitePagesEventIdRoute
  '/site/player/$id': typeof SiteSitePagesPlayerIdRoute
  '/app/events': typeof AppAppPagesEventsIndexRoute
  '/app/events/$id/edit': typeof AppAppPagesEventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/site': typeof SiteRouteRouteWithChildren
  '/logged-in': typeof LoggedInRoute
  '/app/bot-chat': typeof AppAppPagesBotChatRoute
  '/app/identities': typeof AppAppPagesIdentitiesRoute
  '/app/import-bot': typeof AppAppPagesImportBotRoute
  '/app/venues': typeof AppAppPagesVenuesRoute
  '/site/events': typeof SiteSitePagesEventsRoute
  '/site/faction-rankings': typeof SiteSitePagesFactionRankingsRoute
  '/site/rankings': typeof SiteSitePagesRankingsRoute
  '/app/events/new-bot': typeof AppAppPagesEventsNewBotRoute
  '/app/events/new-longshanks': typeof AppAppPagesEventsNewLongshanksRoute
  '/app/events/new-manual': typeof AppAppPagesEventsNewManualRoute
  '/site/event/$id': typeof SiteSitePagesEventIdRoute
  '/site/player/$id': typeof SiteSitePagesPlayerIdRoute
  '/app/events': typeof AppAppPagesEventsIndexRoute
  '/app/events/$id/edit': typeof AppAppPagesEventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/site': typeof SiteRouteRouteWithChildren
  '/logged-in': typeof LoggedInRoute
  '/app/_app-pages/bot-chat': typeof AppAppPagesBotChatRoute
  '/app/_app-pages/identities': typeof AppAppPagesIdentitiesRoute
  '/app/_app-pages/import-bot': typeof AppAppPagesImportBotRoute
  '/app/_app-pages/venues': typeof AppAppPagesVenuesRoute
  '/site/_site-pages/events': typeof SiteSitePagesEventsRoute
  '/site/_site-pages/faction-rankings': typeof SiteSitePagesFactionRankingsRoute
  '/site/_site-pages/rankings': typeof SiteSitePagesRankingsRoute
  '/app/_app-pages/events/new-bot': typeof AppAppPagesEventsNewBotRoute
  '/app/_app-pages/events/new-longshanks': typeof AppAppPagesEventsNewLongshanksRoute
  '/app/_app-pages/events/new-manual': typeof AppAppPagesEventsNewManualRoute
  '/site/_site-pages/event/$id': typeof SiteSitePagesEventIdRoute
  '/site/_site-pages/player/$id': typeof SiteSitePagesPlayerIdRoute
  '/app/_app-pages/events/': typeof AppAppPagesEventsIndexRoute
  '/app/_app-pages/events/$id/edit': typeof AppAppPagesEventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/site'
    | '/logged-in'
    | '/app/bot-chat'
    | '/app/identities'
    | '/app/import-bot'
    | '/app/venues'
    | '/site/events'
    | '/site/faction-rankings'
    | '/site/rankings'
    | '/app/events/new-bot'
    | '/app/events/new-longshanks'
    | '/app/events/new-manual'
    | '/site/event/$id'
    | '/site/player/$id'
    | '/app/events'
    | '/app/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/site'
    | '/logged-in'
    | '/app/bot-chat'
    | '/app/identities'
    | '/app/import-bot'
    | '/app/venues'
    | '/site/events'
    | '/site/faction-rankings'
    | '/site/rankings'
    | '/app/events/new-bot'
    | '/app/events/new-longshanks'
    | '/app/events/new-manual'
    | '/site/event/$id'
    | '/site/player/$id'
    | '/app/events'
    | '/app/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/site'
    | '/logged-in'
    | '/app/_app-pages/bot-chat'
    | '/app/_app-pages/identities'
    | '/app/_app-pages/import-bot'
    | '/app/_app-pages/venues'
    | '/site/_site-pages/events'
    | '/site/_site-pages/faction-rankings'
    | '/site/_site-pages/rankings'
    | '/app/_app-pages/events/new-bot'
    | '/app/_app-pages/events/new-longshanks'
    | '/app/_app-pages/events/new-manual'
    | '/site/_site-pages/event/$id'
    | '/site/_site-pages/player/$id'
    | '/app/_app-pages/events/'
    | '/app/_app-pages/events/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  LoggedInRoute: typeof LoggedInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logged-in': {
      id: '/logged-in'
      path: '/logged-in'
      fullPath: '/logged-in'
      preLoaderRoute: typeof LoggedInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/_site-pages/rankings': {
      id: '/site/_site-pages/rankings'
      path: '/rankings'
      fullPath: '/site/rankings'
      preLoaderRoute: typeof SiteSitePagesRankingsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/site/_site-pages/faction-rankings': {
      id: '/site/_site-pages/faction-rankings'
      path: '/faction-rankings'
      fullPath: '/site/faction-rankings'
      preLoaderRoute: typeof SiteSitePagesFactionRankingsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/site/_site-pages/events': {
      id: '/site/_site-pages/events'
      path: '/events'
      fullPath: '/site/events'
      preLoaderRoute: typeof SiteSitePagesEventsRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/app/_app-pages/venues': {
      id: '/app/_app-pages/venues'
      path: '/venues'
      fullPath: '/app/venues'
      preLoaderRoute: typeof AppAppPagesVenuesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/import-bot': {
      id: '/app/_app-pages/import-bot'
      path: '/import-bot'
      fullPath: '/app/import-bot'
      preLoaderRoute: typeof AppAppPagesImportBotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/identities': {
      id: '/app/_app-pages/identities'
      path: '/identities'
      fullPath: '/app/identities'
      preLoaderRoute: typeof AppAppPagesIdentitiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/bot-chat': {
      id: '/app/_app-pages/bot-chat'
      path: '/bot-chat'
      fullPath: '/app/bot-chat'
      preLoaderRoute: typeof AppAppPagesBotChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/events/': {
      id: '/app/_app-pages/events/'
      path: '/events'
      fullPath: '/app/events'
      preLoaderRoute: typeof AppAppPagesEventsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/site/_site-pages/player/$id': {
      id: '/site/_site-pages/player/$id'
      path: '/player/$id'
      fullPath: '/site/player/$id'
      preLoaderRoute: typeof SiteSitePagesPlayerIdRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/site/_site-pages/event/$id': {
      id: '/site/_site-pages/event/$id'
      path: '/event/$id'
      fullPath: '/site/event/$id'
      preLoaderRoute: typeof SiteSitePagesEventIdRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/app/_app-pages/events/new-manual': {
      id: '/app/_app-pages/events/new-manual'
      path: '/events/new-manual'
      fullPath: '/app/events/new-manual'
      preLoaderRoute: typeof AppAppPagesEventsNewManualRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/events/new-longshanks': {
      id: '/app/_app-pages/events/new-longshanks'
      path: '/events/new-longshanks'
      fullPath: '/app/events/new-longshanks'
      preLoaderRoute: typeof AppAppPagesEventsNewLongshanksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/events/new-bot': {
      id: '/app/_app-pages/events/new-bot'
      path: '/events/new-bot'
      fullPath: '/app/events/new-bot'
      preLoaderRoute: typeof AppAppPagesEventsNewBotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/_app-pages/events/$id/edit': {
      id: '/app/_app-pages/events/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/app/events/$id/edit'
      preLoaderRoute: typeof AppAppPagesEventsIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppAppPagesBotChatRoute: typeof AppAppPagesBotChatRoute
  AppAppPagesIdentitiesRoute: typeof AppAppPagesIdentitiesRoute
  AppAppPagesImportBotRoute: typeof AppAppPagesImportBotRoute
  AppAppPagesVenuesRoute: typeof AppAppPagesVenuesRoute
  AppAppPagesEventsNewBotRoute: typeof AppAppPagesEventsNewBotRoute
  AppAppPagesEventsNewLongshanksRoute: typeof AppAppPagesEventsNewLongshanksRoute
  AppAppPagesEventsNewManualRoute: typeof AppAppPagesEventsNewManualRoute
  AppAppPagesEventsIndexRoute: typeof AppAppPagesEventsIndexRoute
  AppAppPagesEventsIdEditRoute: typeof AppAppPagesEventsIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAppPagesBotChatRoute: AppAppPagesBotChatRoute,
  AppAppPagesIdentitiesRoute: AppAppPagesIdentitiesRoute,
  AppAppPagesImportBotRoute: AppAppPagesImportBotRoute,
  AppAppPagesVenuesRoute: AppAppPagesVenuesRoute,
  AppAppPagesEventsNewBotRoute: AppAppPagesEventsNewBotRoute,
  AppAppPagesEventsNewLongshanksRoute: AppAppPagesEventsNewLongshanksRoute,
  AppAppPagesEventsNewManualRoute: AppAppPagesEventsNewManualRoute,
  AppAppPagesEventsIndexRoute: AppAppPagesEventsIndexRoute,
  AppAppPagesEventsIdEditRoute: AppAppPagesEventsIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface SiteRouteRouteChildren {
  SiteSitePagesEventsRoute: typeof SiteSitePagesEventsRoute
  SiteSitePagesFactionRankingsRoute: typeof SiteSitePagesFactionRankingsRoute
  SiteSitePagesRankingsRoute: typeof SiteSitePagesRankingsRoute
  SiteSitePagesEventIdRoute: typeof SiteSitePagesEventIdRoute
  SiteSitePagesPlayerIdRoute: typeof SiteSitePagesPlayerIdRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteSitePagesEventsRoute: SiteSitePagesEventsRoute,
  SiteSitePagesFactionRankingsRoute: SiteSitePagesFactionRankingsRoute,
  SiteSitePagesRankingsRoute: SiteSitePagesRankingsRoute,
  SiteSitePagesEventIdRoute: SiteSitePagesEventIdRoute,
  SiteSitePagesPlayerIdRoute: SiteSitePagesPlayerIdRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  LoggedInRoute: LoggedInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
