name: Deploy Backend
on:
  push:
    branches:
      - main
      - switch-to-terra

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    environment: prod
    env:
      GCP_PROJECT: ${{ vars.GCP_PROJECT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Set up CA Certificate
        run: |
          printf "%s\n" "${{ secrets.DB_CA_CERT }}" > backend/ca.pem

      - name: Build Backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NODE_EXTRA_CA_CERTS: ca.pem
        working-directory: backend
        run: |
          npm ci
          ./build-for-prod.sh

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:${{ github.sha }} ./backend

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
